SESSION_COOKIE_NAME = "session_id"
CSRF_COOKIE_NAME = "csrf_token"
CSRF_HEADER_NAME = "X-CSRF-Token"

SESSION_TOKEN_BYTES = 32
CSRF_TOKEN_BYTES = 32
SESSION_TOKEN_MAX_LENGTH = 64
CSRF_TOKEN_MAX_LENGTH = 64

CSRF_SAFE_METHODS = frozenset({"GET", "HEAD", "OPTIONS"})

INVALID_SESSION_DETAIL = "Sesion invalida"
PERMISSION_DENIED_DETAIL = "Permiso denegado"
INVALID_CSRF_DETAIL = "Token CSRF invalido"
