CATEGORY_COLUMN = "category"
PRODUCT_NAME_COLUMN = "product_name"
UNIT_COLUMN = "unit"
VARIANT_LABEL_COLUMN = "variant_label"
ATTRIBUTES_COLUMN = "attributes"
PRICE_COLUMN = "price"

REQUIRED_COLUMNS = (CATEGORY_COLUMN, PRODUCT_NAME_COLUMN, UNIT_COLUMN, PRICE_COLUMN)
OPTIONAL_COLUMNS = (VARIANT_LABEL_COLUMN, ATTRIBUTES_COLUMN)
ALL_COLUMNS = REQUIRED_COLUMNS + OPTIONAL_COLUMNS

ATTRIBUTE_PAIR_SEPARATOR = ";"
ATTRIBUTE_KEY_VALUE_SEPARATOR = "="

CSV_EXTENSION = ".csv"
EXCEL_EXTENSION = ".xlsx"

MAX_FILE_SIZE_BYTES = 10 * 1024 * 1024
MAX_DATA_ROWS = 20_000

FIRST_DATA_ROW_NUMBER = 2
