NAME_MAX_LENGTH = 255
INDUSTRY_MAX_LENGTH = 100
STATUS_MAX_LENGTH = 20

USERNAME_MIN_LENGTH = 3
USERNAME_MAX_LENGTH = 80
PASSWORD_MIN_LENGTH = 4
PASSWORD_HASH_MAX_LENGTH = 255

FONT_SIZE_MIN = 1
FONT_SIZE_MAX = 5
FONT_SIZE_DEFAULT = 2

UNIT_ABBREVIATION_MAX_LENGTH = 20

PRICE_PRECISION = 12
PRICE_SCALE = 2

OBSERVATION_MAX_LENGTH = 500

DEFAULT_MINIMUM_STOCK = 10
MAX_STOCK_QUANTITY = 2_147_483_647
