NAME_MAX_LENGTH = 255
INDUSTRY_MAX_LENGTH = 100
STATUS_MAX_LENGTH = 20

USERNAME_MIN_LENGTH = 3
USERNAME_MAX_LENGTH = 80
PASSWORD_MIN_LENGTH = 8
PASSWORD_HASH_MAX_LENGTH = 255

UNIT_ABBREVIATION_MAX_LENGTH = 20
