EMPLEADO = "Empleado"
GERENTE = "Gerente"
ADMINISTRADOR = "Administrador"
DUENO = "Dueño"

ROLE_HIERARCHY = (EMPLEADO, GERENTE, ADMINISTRADOR, DUENO)
ROLE_RANK = {name: rank for rank, name in enumerate(ROLE_HIERARCHY)}

INITIAL_ROLES = ROLE_HIERARCHY
